// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v5.26.1
// source: crawl.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// CrawlClient is the client API for Crawl service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type CrawlClient interface {
	Work(ctx context.Context, in *CrawlRequest, opts ...grpc.CallOption) (*CrawlResponse, error)
}

type crawlClient struct {
	cc grpc.ClientConnInterface
}

func NewCrawlClient(cc grpc.ClientConnInterface) CrawlClient {
	return &crawlClient{cc}
}

func (c *crawlClient) Work(ctx context.Context, in *CrawlRequest, opts ...grpc.CallOption) (*CrawlResponse, error) {
	out := new(CrawlResponse)
	err := c.cc.Invoke(ctx, "/tempotaletl.Crawl/Work", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// CrawlServer is the server API for Crawl service.
// All implementations must embed UnimplementedCrawlServer
// for forward compatibility
type CrawlServer interface {
	Work(context.Context, *CrawlRequest) (*CrawlResponse, error)
	mustEmbedUnimplementedCrawlServer()
}

// UnimplementedCrawlServer must be embedded to have forward compatible implementations.
type UnimplementedCrawlServer struct {
}

func (UnimplementedCrawlServer) Work(context.Context, *CrawlRequest) (*CrawlResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Work not implemented")
}
func (UnimplementedCrawlServer) mustEmbedUnimplementedCrawlServer() {}

// UnsafeCrawlServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to CrawlServer will
// result in compilation errors.
type UnsafeCrawlServer interface {
	mustEmbedUnimplementedCrawlServer()
}

func RegisterCrawlServer(s grpc.ServiceRegistrar, srv CrawlServer) {
	s.RegisterService(&Crawl_ServiceDesc, srv)
}

func _Crawl_Work_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CrawlRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CrawlServer).Work(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/tempotaletl.Crawl/Work",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CrawlServer).Work(ctx, req.(*CrawlRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Crawl_ServiceDesc is the grpc.ServiceDesc for Crawl service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Crawl_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "tempotaletl.Crawl",
	HandlerType: (*CrawlServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Work",
			Handler:    _Crawl_Work_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "crawl.proto",
}
